### ISSUE TITLE
Remove dependencies on yii-core

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/db#14]
If we really want this to be useful independently of `yii-core` we should remove the application from the test suite.

We can't guarantee that it works properly without the core if we still initialize our singletons like `Yii::$container` and `Yii::$app` during testing.

**Comment by hiqsol** [comment]
That's very true!
But I think we could start with getting the build completely fixed by easier way (with core).
And then remove core.

**Comment by terabytesoftw** [comment]
Done.
