### ISSUE TITLE
[2.1] Make all query properties protected

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/db#19]
I'd like to make all query properties like `$where`, `$limit` and so on protected.

### What steps will reproduce the problem?
I have a model (or multiple models) that support soft delete.
I'd like to limit how these are queried by implementing a custom `ActiveQuery` class.

Some things I do or would like to do:
- [X] Filter deleted records by default
- [X] Throw an exception on the `->where()` function, for my models I want to enforce only using `andWhere`.
- [ ] Disable direct modification of the query.

### What is the expected result?
I expect to have control over my own query class.

### What do you get instead?
Since most properties are public there is no control, anyone could be writing to them directly.
I think the design would be cleaner and more powerful if these properties would be protected.
Since these classes are subclasses of `Component` they have support for magic getters which would provide a backwards compatible upgrade path in most cases.

**Comment by terabytesoftw** [comment]
Done, add setters, getters, property all protected.
