### ISSUE TITLE
Take implicit commit into account when determining if transaction is active

### ISSUE THREAD

**Issue by samdark** [yiisoft/db#202]
See https://github.com/yiisoft/yii2/pull/18407#discussion_r530507105

**Comment by Tigrov** [comment]
Is it solved?

There is a test https://github.com/yiisoft/db-mysql/blob/65497c39384f628d11755f8d6e52db000def30af/tests/PdoConnectionTest.php#L96-L109

**Comment by samdark** [comment]
Yes. Seems so.
