### ISSUE TITLE
QueryDataReader

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/db#239]
Доброго дня. Т.к. для большинства своих задач мне хватает обычного [Query/ActiveQuery](https://github.com/yiisoft/db/) и в тоже время есть необходимость простенько отобразить данные с помощью [DataView виджетов](https://github.com/yiisoft/yii-dataview/), которые требуют OffsetPaginator, который в свою очередь требует на вход ReadableDataInterface. Соответственно нельзя просто закинуть [Db\DataReader](https://github.com/yiisoft/db/blob/master/src/Data/DataReader.php), т.к. он не реализует этот интерфейс.

Таким образом для себя написал простенький QueryDataReader, который по сути является "синтаксичесим сахаром", т.к. все эти манипуляции можно выполнить вне ридера и закинуть в DataView::widget OffsetPaginator($query->all), но с его помощью это получается однообразно. 

Живой пример использования:
`
$filter = new All(
            (new Equals("type_id", $typeId))->ignoreNull(true),
            (new Equals("country_id", $countryId))->ignoreNull(true),
            (new Equals("parent_id", $parentId))->ignoreNull(true)
        );

        $sort = Sort::only([
            'id',
            'title',
            'type',
        ])->withOrder([
            'id' => 'asc'
        ]);

        $dataReader =(new QueryDataReader($query))
            ->withFilter($filter)
            ->withSort($sort);
`

[Query.zip](https://github.com/yiisoft/data/files/7237186/Query.zip)

P.S. сортировка пока работает не так как хотелось-бы

**Comment by samdark** [comment]
Transferred to db since we can't have a dependency on DB in data package.

**Comment by samdark** [comment]
@Gerych1984 would you please adopt the class for this package? I think that current Yii DB DataReader will be eventually removed.

**Comment by Gerych1984** [comment]
> @Gerych1984 would you please adopt the class for this package? I think that current Yii DB DataReader will be eventually removed.

Попробую завтра. Честно говоря dev-tools пока даже не клонировал, но вроде как завтра, после показа промежуточных результатов, будет время до выходных навести у себя порядок с тем что есть. Как-раз для этого и написалданный ридер )
