### ISSUE TITLE
yii\db\Command logging queries with level 'info' instead 'trace' in execute() and queryInternal()

### ISSUE THREAD

**Issue by only-victor** [yiisoft/db#25]
### What is wrong?

The methods execute() and queryInternal() have logging queries by Yii::info($rawSql, ____METHOD___);
Why 'info' ?
I think it must be 'trace' level.
### What I propose?

Yii::trace($rawSql, ____METHOD___);
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.8 |
| PHP version | 5.6 |
| Operating system | ArchLinux |

**Comment by rob006** [comment]
It is already possible to disable  logging of these queries by setting `Connection::$enableLogging` to `false`. 

Related: https://github.com/yiisoft/yii2/pull/16671.
