### ISSUE TITLE
Allow null as duration in SchemaCache (QueryCache?)

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/db#257]
Goog day. In my case table schema not changed between releases on production and for special cases i have opportunity to manual clear it. But now i can't set duration to infinity (null) - only int. Thanks

**Comment by terabytesoftw** [comment]
https://github.com/yiisoft/db/blob/f3f415ee7193b405d91b018f53d408f138d799fa/src/Cache/SchemaCache.php#L109 

setDuration 0 is infinity.

**Comment by Gerych1984** [comment]
> https://github.com/yiisoft/db/blob/f3f415ee7193b405d91b018f53d408f138d799fa/src/Cache/SchemaCache.php#L109
> 
> 
> https://github.com/yiisoft/db/blob/f3f415ee7193b405d91b018f53d408f138d799fa/src/Cache/QueryCache.php#L118
> 
> setDuration `0` is infinity.

Yes, that wrote on PhpDOC. But in current Cache adapter (Apcu in my case) 0 equals self::TTL_EXPIRED in `normalizeTtl`. Only `null` equals self::TTL_INFINITY
