### ISSUE TITLE
[Refactoring todo] Remove retryHandler from current implementation

### ISSUE THREAD

**Issue by darkdef** [yiisoft/db#261]
In current implementation we have retryHandler in function `internalExecute`. 
Retry - is responsibility of user.

Need remove this code from Command.php

**Comment by mamadza** [comment]
is Retry for purpose of DeadLock or etc ? if yes , it's good thing to implement it in any approach

**Comment by darkdef** [comment]
In current implementation - retryHandler may be using for all sql queries.

**Comment by darkdef** [comment]
will not be decided
