### ISSUE TITLE
Wrong ColumnSchema::getColumnPhpType for decimal type

### ISSUE THREAD

**Issue by Gerych1984** [yiisoft/db#264]
Good day. I have my own custom realization for `AR::save` with ignored not changed rows (for multiple updates from cron). But today i found that it sometimes not works. It was happend if row have decimal DB type, because `ColumnSchema::getColumnPhpType` returns string for  this type (mybe some other types). And as result i have for example string **"10"** as current value and string **"10.00"** as oldValue.

**Comment by terabytesoftw** [comment]
Could you write the structure of the table, and if the error occurs in `AR` or `DB`, to reproduce it correctly, thanks.

**Comment by Gerych1984** [comment]
> Could you write the structure of the table, and if the error occurs in `AR` or `DB`, to reproduce it correctly, thanks.

[src.zip](https://github.com/yiisoft/db/files/7953031/src.zip)

Hi - this attached archive contains migration, my abstract record, AR to work with test table and test command. i'm using pgsql and i have that test result. As you can see - decimal returns and casted to string instead of float
![Снимок экрана от 2022-01-27 21-40-47](https://user-images.githubusercontent.com/90403480/151423577-9fdaea55-96ed-4f75-b7f5-e4821bcad823.png)

**Comment by darkdef** [comment]
@Gerych1984 check please
