### ISSUE TITLE
Schema.php - ideas of refactoring

### ISSUE THREAD

**Issue by darkdef** [yiisoft/db#265]
1. **public function getPdoType($data): int**
Need refactoring and remove this method

2. **public function getLastInsertID(string $sequenceName = ''): string**
Need refactoring and remove this method, because not all dbms supported this

3. **public function createSavepoint(string $name): void
public function releaseSavepoint(string $name): void
public function rollBackSavepoint(string $name): void
public function setTransactionIsolationLevel(string $level): void**
move to class Transation?

4. **public function insert(string $table, array $columns)**
@todo - need refactoring:
-  $this->getTableSchema($table) - maybe null
- $tableSchema->getColumn($name) - maybe null
- $tableSchema->getColumn($name) - maybe null
- not all dbms support lastInsertId - method getLastInsertID must be renamed, refactoring or removed.
In mssql SCOPE_IDENTITY() - @see https://docs.microsoft.com/ru-ru/dotnet/framework/data/adonet/retrieving-identity-or-autonumber-values
And maybe move this method to other class?

5. **public function quoteValue($str)
public function quoteTableName(string $name): string
public function quoteColumnName(string $name): string
public function quoteSimpleTableName(string $name): string
public function quoteSimpleColumnName(string $name): string
public function unquoteSimpleTableName(string $name): string
public function unquoteSimpleColumnName(string $name): string**
need remove and create QuoterHelper for this functional (also remove from Connection). Example of QuoteHelper:
https://github.com/darkdef/dbal/blob/main/src/Schema/QuoterInterface.php
https://github.com/darkdef/dbal/blob/main/dbms/Mysql/Schema/Quoter.php

6. **public function getRawTableName(string $name): string**
move to QuoterHelper?

7. **public function convertException(\Exception $e, string $rawSql): Exception**
move it to a separate class

8. **public function isReadQuery(string $sql): bool**
move it to a separate class

9. Do we need separate createQueryBuilder() and getQueryBuilder()?

**Comment by samdark** [comment]
2. Do you want to force users to specify ID explicitly? Sequences aren't supported by all RDBMs either.
3. I'd move that to connection since the scope of SQL generated is current connection.
4. Yes, should be moved to another class. Definitely doesn't belong to schema. Either connection or query builder.

**Comment by darkdef** [comment]
Not actual
