### ISSUE TITLE
Move DSN  from `PDODriverInterface` to `ConnectionInterface`

### ISSUE THREAD

**Issue by vjik** [yiisoft/db#329]
This is need for get information from any connection instead of PDO only.

Example of usage: https://github.com/yiisoft/yii-db-migration/blob/993e9d33a8b0ecc9d209511aaf4ee13de0d7a4fe/src/Service/Database/ListTablesService.php#L52

**Comment by terabytesoftw** [comment]
closed from https://github.com/yiisoft/db/pull/330
