### ISSUE TITLE
Command testBindParamValue fails

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/db#40]
Here $float_val = 1.23, instead db column type is defined as double(4,3), so its value is 1.230.

https://github.com/yiisoft/db/blob/1351c16e684a6f1858b9034fdac6ad9ef3fc231c/tests/unit/CommandTest.php#L207

When checked equality, test fails.

**Comment by FabrizioCaldarelli** [comment]
According to:

If I change that line to:
https://phpunit.de/manual/6.5/en/appendixes.assertions.html

`        
$this->assertEquals((float)$floatCol, (float) $row['float_col']);
`

test succeded.

Are you agree to update that line?

**Comment by machour** [comment]
If that test was copied over from yii2 and was working without casting to float, we better understand what changed and why. 

Could you check how it's done in yii2?

**Comment by FabrizioCaldarelli** [comment]
Explained here: https://github.com/yiisoft/db/pull/44#pullrequestreview-188864375
