### ISSUE TITLE
Move $config empty condition check inside AbstractContainer::configure()

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/db#42]
I've found many times this souces:

```
        if (!empty($config)) {
            \yii\di\AbstractContainer::configure($this, $config);
        }
```
For example, here:
https://github.com/yiisoft/db/blob/54e7a7ef9f7683bb641a13574c5c34cbd8c5dc61/src/Query.php#L1308

Should not be better that $config empty condition check was done inside AbstractContainer::configure, so we should have only:

```
\yii\di\AbstractContainer::configure($this, $config);
```

**Comment by samdark** [comment]
As far as I remember, it was performance optimization: `empty()` call is cheaper than method call. We can probably measure it with basic app and, if it's negligible, move it to the method.

**Comment by FabrizioCaldarelli** [comment]
You are saying that 

```
        if (!empty($config)) {
            \yii\di\AbstractContainer::configure($this, $config);
        }
```

is cheaper that

```
class AbstractContainer 
{
        function configure($object, $config = [])
       {
               if (!empty($config)) {
                       // ....
               }
       }
}
```
?

Anyway the question is that I think that if we check $config content inside ::configure is always a good thing, because developer could forget to do it.

**Comment by samdark** [comment]
There are two cases:

1. When config is empty we're just calling `empty()`.
2. When config is not empty we're calling both `empty()` and a method.

With your change we'll call both all the time.

But overall I don't think that matters.

**Comment by samdark** [comment]
https://github.com/yiisoft/di/pull/65#discussion_r244886030

Can't we just remove these checks?

**Comment by FabrizioCaldarelli** [comment]
If my PR is approved, I'll remove $config content check from everywhere ::configure() is called,
that it is superfluous.

**Comment by samdark** [comment]
But the PR doesn't make sense to me. See comment.

**Comment by FabrizioCaldarelli** [comment]
Ok, but then the same check could be removed from everywhere and simple calling:

`            
\yii\di\AbstractContainer::configure($this, $config);
`

such as here: https://github.com/yiisoft/db/blob/54e7a7ef9f7683bb641a13574c5c34cbd8c5dc61/src/Query.php#L1308

**Comment by samdark** [comment]
Yes, I think so.

**Comment by FabrizioCaldarelli** [comment]
What if config is null?

**Comment by rob006** [comment]
There is already a typehint in method signature - `null` cannot be passed as `iterable`, so there is no need to check type again. 

We could improve signature even more using `object` type for `$object` parameter:

```php
public static function configure(object $object, iterable $config)
```

**Comment by samdark** [comment]
Yes.
