### ISSUE TITLE
Missing $charset in \yii\db\Connection

### ISSUE THREAD

**Issue by FabrizioCaldarelli** [yiisoft/db#50]
Current version of \yii\dbConnection is missing $charset property.

This is needed in db-pgsql tests, here:
https://github.com/yiisoft/db-pgsql/blob/2508fee50c1c65705015c2546bc980e8277c8720/tests/unit/ActiveRecordTest.php#L129

I have read  an issue (https://github.com/yiisoft/db/issues/7) that $charset had to be moved in Schema class, but it is not even here.

What is final thought?

**Comment by samdark** [comment]
Tests should be adjusted to use multiple connections. Each for different charset.

**Comment by FabrizioCaldarelli** [comment]
Do we want support charset also in configuration?

```
$config = [
    'databases' => [
        'pgsql' => [
            'dsn' => 'pgsql:host=postgres;dbname=yiitest;port=5432;',
            'username' => 'postgres',
            'password' => 'postgres',
            'fixture' => __DIR__ . '/postgres.sql',
            'charset' => 'utf8'
        ],
    ],
];
```

I'll put setCharset inside \yii\db\Connection, to change it in runtime.

**Comment by samdark** [comment]
Configuration as well, of course. It can be set via DSN currently but separate entry won't hurt. Do you have a valid case for changing charset at runtime?

**Comment by FabrizioCaldarelli** [comment]
>  It can be set via DSN currently but separate entry won't hurt.

Currently, in Yii2, it is handled in initConnection:

```php
    protected function initConnection()
    {
        $this->pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
        if ($this->emulatePrepare !== null && constant('PDO::ATTR_EMULATE_PREPARES')) {
            $this->pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, $this->emulatePrepare);
        }
        if ($this->charset !== null && in_array($this->getDriverName(), ['pgsql', 'mysql', 'mysqli', 'cubrid'], true)) {
            $this->pdo->exec('SET NAMES ' . $this->pdo->quote($this->charset));
        }
        $this->trigger(self::EVENT_AFTER_OPEN);
    }
```

In Yii3, I can't find where it is handled.

> Do you have a valid case for changing charset at runtime?

No, I have not a valid case. I'll skip it for the moment.

**Comment by samdark** [comment]
Yes. In Yii 3.0 it was removed because it isn't necessary to do `SET NAMES` query anymore since it's well-handled in PHP 7 PDO.

**Comment by FabrizioCaldarelli** [comment]
How is this well-handled in PHP 7 PDO ? Have not I to call pdo->exec to SET NAMES?

**Comment by samdark** [comment]
https://github.com/yiisoft/db/issues/7#issuecomment-428287450

**Comment by FabrizioCaldarelli** [comment]
This reference is valid only for MySQL. And for Postgres and others?

**Comment by samdark** [comment]
Should be the same.

**Comment by samdark** [comment]
Needs to be checked. I may be wrong. PostgreSQL is a good candidate for checking. There's no `charset` DSN part documented.

**Comment by FabrizioCaldarelli** [comment]
If PostgreSQL is not supported, how do we go about this?

What do you think if did we keep old working code? Otherwise we would have benefits only on mysql.

**Comment by samdark** [comment]
> If PostgreSQL is not supported, how do we go about this?

1. Returning `SET NAMES`.
2. Trying to use charset of DSN where supported instead of `SET NAMES`.

**Comment by FabrizioCaldarelli** [comment]
1. Restoring

```
        if ($this->charset !== null && in_array($this->getDriverName(), ['pgsql', 'cubrid'], true)) {
            $this->pdo->exec('SET NAMES ' . $this->pdo->quote($this->charset));
        }
```

in initConnection?

2. In previous code I removed mysql from driverName check.

Finally, changing dinamically charset is required by tests. So I think that it should be better implementing charset dynamic changes inside \yii\db\Connection.

**Comment by FabrizioCaldarelli** [comment]
> Configuration as well, of course. It can be set via DSN currently but separate entry won't hurt. Do you have a valid case for changing charset at runtime?

It is not possible without subclassing \yii\db\Connection.

https://github.com/yiisoft/db/blob/7aef171c019f943e26482ae69e9d8a50d9449845/tests/unit/DatabaseTestCase.php#L87

In fact when I pass this $config

```
        'pgsql' => [
            'dsn' => 'pgsql:host=postgres;dbname=yiitest;port=5432;',
            'username' => 'postgres',
            'password' => 'postgres',
            'fixture' => __DIR__ . '/postgres.sql',
            'charset' => 'utf8'
        ],
```

returns

` "Setting unknown property: yii\db\Connection::charset"`

I thought 2 solutions:

1) Restore `$charset` in \yii\db\Connection;
2) Move `charset` in dns, so it will work immediately in MySQL, but we should extract with regexp and use it in initConnection() for other dbms;

**Comment by samdark** [comment]
Yes. Let's have it back.
