### ISSUE TITLE
Class 'yii\base\Component' not found

### ISSUE THREAD

**Issue by lichunqiang** [yiisoft/db#56]
### What steps will reproduce the problem?

I just want only use `yiisoft/db`, after install `composer require yiisoft/db:dev-master`, The exception throwed.

### What is the expected result?

can use __db__ component normally.

### What do you get instead?

Fatal error occured.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 3.0.?
| PHP version      | php7.1
| Operating system | Centos

BTW:  Emmm... What's the time to use yii3.0 components individually ?

**Comment by samdark** [comment]
Not right now.
