### ISSUE TITLE
Please make Query.php overridable.

### ISSUE THREAD

**Issue by andrew-svirin** [yiisoft/db#57]
I have a problem withh overriding class. I know my code is not pretty good, but it have sence anyeay.

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16
| PHP version      |  7.0
| Operating system | Debian
[yii2-query.patch.txt](https://github.com/yiisoft/yii2/files/2840626/yii2-query.patch.txt)

**Comment by AndriySvirin** [comment]
My pleasure. Thanks for listening and unerstanding.

**Comment by machour** [comment]
@AndriySvirin thank you for your contribution, I have opened the two pull requests on your behalf.

It would be great if you could add some tests to make sure everything works as expected when overriding the `Query` class.

Feel free to set up the test on your yii2 copy and post the patch here, I'll update Yii3 repos accordingly.
