### ISSUE TITLE
2.0.16 breaks certain select2 fields validation in active form

### ISSUE THREAD

**Issue by hooman-pro** [yiisoft/db#59]
@licanulla commented on [Tue Feb 19 2019](https://github.com/yiisoft/yii2/issues/17147)

Just found that since upgrade 2.0.16 my select2 fields with ajax option are no longer validated. Those with preset data still are. No JS errors in console. Downgraded to 2.0.15.1 and got my forms working again.

---

@rob006 commented on [Tue Feb 19 2019](https://github.com/yiisoft/yii2/issues/17147#issuecomment-465290450)

Probably duplicate of https://github.com/yiisoft/yii2/issues/17111

How do you generate AJAX response for select2 widget?

---

@licanulla commented on [Tue Feb 19 2019](https://github.com/yiisoft/yii2/issues/17147#issuecomment-465295681)

No AJAX calls in my case. The client-side validation is broken somehow so when the form is loaded and you hit "submit" button, those select2 fields (with `ajax` option) left empty aren't marked as required, while they are and the form is initialized with those fields as required.

---

@rob006 commented on [Wed Feb 20 2019](https://github.com/yiisoft/yii2/issues/17147#issuecomment-465322828)

You need to give some code to reproduce this issue.

**Comment by machour** [comment]
?
