### ISSUE TITLE
Connection createTransaction() is part of the public interface of connection

### ISSUE THREAD

**Issue by cebe** [yiisoft/db#638]
### What steps will reproduce the problem?

Connection createTransaction() is part of the public interface of connection. Have not checked the consequences yet, but there is `beginTransaction()` which is what a user should call to start a new transaction, having `createTransaction()` also there could be confusing, it should ideally be a protected method which is implemented in the specific connection classes to create the transaction class for that connection implementation.

**Comment by samdark** [comment]
I've seen this as well. There was an example about that there could be a need to create a transaction without starting it right away. @darkdef do you remember the use-case?

**Comment by darkdef** [comment]
Example 1
$transaction = $db->getTransaction();
// Panic, what happened, why the transaction has already started. Who did it ?
if (!$transaction) {
    $transaction = $db->createTransaction();
}
$transaction->begin();
...
$transaction->commit();

vs

Example 2
$transaction = $db->beginTransaction() // Silently join someone else's transaction if it is started
.....
$transaction->commit();

I think - user can needed both cases

**Comment by samdark** [comment]
Let it be.
