### ISSUE TITLE
Query::__toString() claims to return the SQL representation, but it does not

### ISSUE THREAD

**Issue by cebe** [yiisoft/db#642]
### What steps will reproduce the problem?

https://github.com/yiisoft/db/blob/3931c4937205afd4460dfe870f56e6cac72d1f7e/src/Query/Query.php#L96-L102

instead of returning the SQL, it returns `serialize($this);`

### What is the expected result?

not sure, but the methods seems not very useful and it does not match the documentation in the way it is now.

**Comment by samdark** [comment]
Good catch. @darkdef, @terabytesoftw what's the purpose of getting serialized represenation when converting it to string?

**Comment by cebe** [comment]
Seems this has been added in yii2, but I don't see any reason for it. https://github.com/yiisoft/yii2/commit/5afe0a0d36cf9bba68a7424ce122aa79c03522c8 looks like it was merged accidentally. Btw, why is there a 3.0.0-alpha tag in the yii2 repo?

**Comment by vjik** [comment]
SQL is more expected result of `__toString()`

**Comment by samdark** [comment]
> Btw, why is there a [3.0.0-alpha](https://github.com/yiisoft/yii2/releases/tag/3.0.0-alpha1) tag in the yii2 repo?

Because of an afterparty in Kiev. @SilverFire knows ;)

We should remove the tag to avoid confusion but last time I've asked @hiqsol and @SilverFire, it was used.
