### ISSUE TITLE
Naming inconsistency - `TableSchema::compositeFk()`

### ISSUE THREAD

**Issue by arogachev** [yiisoft/db#665]
https://github.com/yiisoft/db/blob/857f0a855bb22e5c230114578baf585d50458578/src/Schema/TableSchemaInterface.php#L215

https://github.com/yiisoft/db/blob/857f0a855bb22e5c230114578baf585d50458578/src/Schema/TableSchemaInterface.php#L204

https://github.com/yiisoft/db/blob/857f0a855bb22e5c230114578baf585d50458578/src/Schema/TableSchemaInterface.php#L121

**Comment by samdark** [comment]
I see no inconsistency here in the naming itself. FK always points from a column to another column. PK does not.

**Comment by darkdef** [comment]
FK - correct abbreviation
we use function with name getRawSql. Sql it's abbreviation. And function don't have a name getRawStructuredQueryLanguage

**Comment by darkdef** [comment]
You rigth. Need change name to compositeForeignKey

**Comment by darkdef** [comment]
Completed
