### ISSUE TITLE
add into insert and batchisert new parameter

### ISSUE THREAD

**Issue by dizews** [yiisoft/db#67]
Hello.
Sometimes I need to insert or update rows. I can do it using 'ON DUPLICATE KEY UPDATE'.

what do you think?

## Funding
* You can sponsor this specific effort via a [Polar.sh](https://polar.sh) pledge below
* We receive the pledge once the issue is completed & verified

<a href="https://polar.sh/yiisoft/db/issues/67">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/yiisoft/db/issues/67/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/yiisoft/db/issues/67/pledge.svg">
</picture>
</a>

**Comment by Tigrov** [comment]
There is `butchInsert()` and need `batchUpsert()`, see #92
