### ISSUE TITLE
Auto generate names for primary keys, foreign keys, indexes

### ISSUE THREAD

**Issue by arogachev** [yiisoft/db#672]
Cycle implementation just for comparison:

```php
$schema = $table->getSchema();
$schema->string('parent', 128)->nullable(false);
$schema
    ->foreignKey(['parent'])
    ->references($this->itemsTable, ['name']);
$schema->save();
```

As a developer, I don't want to spent extra time to think about naming pattern, etc.

**Comment by darkdef** [comment]
We live in the real world and there will be problems with name generation for "field_name" and "field name" and "fieldName" should be different.  (mssql fields may contain idn symbols)
 This is the simplest case.  How to correctly delete the generated index and not make a mistake?

**Comment by samdark** [comment]
https://dev.mysql.com/doc/refman/5.7/en/identifier-length.html#:~:text=Aliases%20for%20column%20names%20in,alias%20length%20of%20256%20characters).

**Comment by samdark** [comment]
That's a problem for meaningful generated names I've personally hit. That's why Doctrine uses generated name that look like `IDX_626EE072C7C2CBA` and are not really meaningful at all.

**Comment by samdark** [comment]
PostgreSQL limit is 63 characters but it's even worse. It doesn't error but truncate the name automatically.

**Comment by vjik** [comment]
Seems, autogeneration for this case is bad idea:
- difficult for implementation;
- potential different key names.
