### ISSUE TITLE
Get DB type without size

### ISSUE THREAD

**Issue by arogachev** [yiisoft/db#695]
Related - #694.

**Comment by arogachev** [comment]
This is a separate issue. 

Example:

`getDbType()`- `varchar(255)`.
`getSize()` - `255`.
`???` - `varchar`.

**Comment by vjik** [comment]
What is case when need type without size?

**Comment by Tigrov** [comment]
In `db-pgsql` and `db-oracle` (depends of type) `getDbType()` returns type without size.

**Comment by Tigrov** [comment]
I'd store pure db type `varchar` in `$dbType`.
And have a method to generate the complete db type `varchar(255)`

**Comment by Tigrov** [comment]
Now `getDbType()` returns clear db type, for example `varchar` instead of `varchar(255)`
