### ISSUE TITLE
Executing many commands with missing required parameters dont throw error 

### ISSUE THREAD

**Issue by KeremArdicli** [yiisoft/db#704]
### What steps will reproduce the problem?
Create a DB instance for the users table wihch has id/username/email columns. Make all of the columns required.
Run the code below.

```php
$transaction = $db->createTransaction();

try {
    $db
        ->createCommand('INSERT INTO {{%users}} ([[id]], [[username]]) VALUES (:id, :user)')
        ->bindValues([':id' => 1, ':user' => "User Name"])
        ->execute();

} catch (Exception $e) {
    $transaction->rollBack();
    var_dump($e->getMessage());
}
```

### What is the expected result?
Since email columns is required it should throw SQL error.

### What do you get instead?
Code just adds a row to the DB. Required values are populated automatically based on data type.

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 1.0.?
| PHP version      | 8.1.1
| Operating system | Win 10 22H2

**Comment by samdark** [comment]
https://github.com/yiisoft/db/pull/703

**Comment by samdark** [comment]
> Code just adds a row to the DB. Required values are populated automatically based on data type.

That means you likely use MySQL and that the mode you use is set up like that. In this case exception will never happen.

**Comment by samdark** [comment]
@KeremArdicli is that correct?

**Comment by KeremArdicli** [comment]
I  use MariaDB yet you are right. Local setup is working like so. I have not tried it on prod server. This can be closed without any further edo
