### ISSUE TITLE
Split yii\db\QueryBuilder into separate simpler classes

### ISSUE THREAD

**Issue by agilov** [yiisoft/db#75]
Its just an idea to make yii\db\QueryBuilder more SRP than it is now.
What if make separate classes for SelectBuilder, InsertBuilder, UpdateBuilder e.t.c
They can be much better to use and understand than the monster yii\db\QueryBuilder
Please say what you think about it

**Comment by darkdef** [comment]
Complete in some PR's and merged to master:
DDL, DML, DQL builders
