### ISSUE TITLE
`Query::count()` can return `int|string` but always returns `int`

### ISSUE THREAD

**Issue by Tigrov** [yiisoft/db#753]
`Query::count()` can return `int|string`

https://github.com/yiisoft/db/blob/fb4c084f5389cc1cd6718f8c74989601506f993c/src/Query/QueryFunctionsInterface.php#L39-L44

But always returns `int`

https://github.com/yiisoft/db/blob/fb4c084f5389cc1cd6718f8c74989601506f993c/src/Query/Query.php#L294-L300

**Comment by vjik** [comment]
Done by #777
