### ISSUE TITLE
Remove `$withColumn` parameter from `getTableNameParts()`

### ISSUE THREAD

**Issue by Tigrov** [yiisoft/db#757]
https://github.com/yiisoft/db/blob/b259119a211a3855c4d3c34ddfe2bed7e4fe9907/src/Schema/Quoter.php#L87-L92

Suggestion to remove the second parameter of `getTableNameParts(string $name, bool $withColumn = false)`

Instead, add method `getColumnNameParts()` if necessary.

**Comment by vjik** [comment]
Does `getTableNameParts with `$withColumn` parameter equal to true somewhere used now?

**Comment by Tigrov** [comment]
In one place https://github.com/yiisoft/db/pull/746/files#diff-697d8c4d18282e94c125fbb9302841ce34c6f6bbe6a4406cd57b371ca9e145aeL470

But it does not work as expected (test https://github.com/yiisoft/db/pull/744)

Removed this use in PR https://github.com/yiisoft/db/pull/746

**Comment by Tigrov** [comment]
Added to issue #767
