### ISSUE TITLE
`CommandInterface::getRawSQL()` - using in production / alternative

### ISSUE THREAD

**Issue by arogachev** [yiisoft/db#759]
What are the edge cases when incorrect results are returned? I tested it and It works so far.

**Comment by Tigrov** [comment]
The answer is in the code of `getRawSql()`

https://github.com/yiisoft/db/blob/master/src/Command/AbstractCommand.php#L353

https://github.com/yiisoft/db/blob/master/src/Command/AbstractCommand.php#L366

This will not work with `resource`s and `Expression`s with params.

**Comment by vjik** [comment]
1) Why need skip this values: `!is_object($value) && !is_resource($value)` ?

2) Should we build instances of `ExpressionInterface` via expression builder ?

@darkdef @terabytesoftw @Tigrov

**Comment by Tigrov** [comment]
> 1. Why need skip this values: `!is_object($value) && !is_resource($value)` ?
> 2. Should we build instances of `ExpressionInterface` via expression builder ?

1. `resource` can be converted in hexadecimal string format, this is different for each DBMS
For `Param` also if it has `LOB` type
https://github.com/yiisoft/db/blob/39872b193b0dfeadd4fd6b2629101a8b61e18a36/src/Command/AbstractCommand.php#L353-L356
About `is_object($value)` I did not see that `object` (not `ExpressionInterface`) can be passed as value. Perhaps for non-PDO implementations?

2. This will return expression without params. Possibly realize `ExpressionInterface::getRawSql()` and replace placeholders with params.
https://github.com/yiisoft/db/blob/39872b193b0dfeadd4fd6b2629101a8b61e18a36/src/Expression/Expression.php#L35-L38

**Comment by vjik** [comment]
> 1. Resource can be converted in hexadecimal string format, this is different for each DBMS

Are there any cases when we need to send a resource via parameters to SQL?

> 2. This will return expression without params ...

May be use `ExpressionBuilder` for convert instance of `ExpressionInterface` to string?

**Comment by Tigrov** [comment]
> Are there any cases when we need to send a resource via parameters to SQL?

Saving data from an open file to db. This should be faster and use less memory compared to reading the file into a string and then passing the string to db.

> May be use `ExpressionBuilder` for convert instance of `ExpressionInterface` to string?

When use `ExpressionBuilder` it returns string with placeholders but without values,
e.g. for `new Expression('field = :value', ['value' => 1])` `ExpressionBuilder` returns `'field = :value'` (the same as current)
Needs a new method to replace placeholders to values.

**Comment by Tigrov** [comment]
> > May be use `ExpressionBuilder` for convert instance of `ExpressionInterface` to string?
> 
> When use `ExpressionBuilder` it returns string with placeholders but without values, e.g. for `new Expression('field = :value', ['value' => 1])` `ExpressionBuilder` returns `'field = :value'` (the same as current) Needs a new method to replace placeholders with values.

Perhaps there is no problem with `Expression` inside `CommandInterface::getRawSQL()`.

In all that cases when `Expression` is passed as a value of `$params` it sould not have extra params inside the expression. This can be only a string which will substitute the placeholder in SQL.

But for that cases when user want to pass params inside expressions, then need to use `ExpressionBuilder` and replace palceholders using the following code

https://github.com/yiisoft/db/blob/39872b193b0dfeadd4fd6b2629101a8b61e18a36/src/Command/AbstractCommand.php#L373-L376

Then the method will support not only `Expression` objects but any `ExpressionInterface` instance.

**Comment by vjik** [comment]
Should `getRawSql()` returns correct SQL?

Seems, not all cases is will be so. For example, resource usage. So far, resources or objects skipped, but may be need add them to raw sql as special words?

**Comment by vjik** [comment]
@Tigrov Create issue, please.

**Comment by vjik** [comment]
What about objects and resources as param value? How process them?

**Comment by Tigrov** [comment]
* `resource` can be converted in hexadecimal string format, this is different for each DBMS.
https://www.postgresql.org/docs/current/datatype-binary.html
https://dev.mysql.com/doc/refman/8.0/en/hexadecimal-literals.html
[https://www.sqlite.org/lang_expr.html#literal_values_constants_](https://www.sqlite.org/lang_expr.html#literal_values_constants_)

* For PDO `objects` can be
  1. `ExpressionInterface` => use `ExpressionBuilder`
  2. `Stringable` => use `(string)$value`

* For non-PDO needs to see. Perhaps it will be driver-own implementation of `getRawSql()`

**Comment by vjik** [comment]
@Tigrov Seems, it is another issue and then we can close this issue, right?
