### ISSUE TITLE
Allow use `DMLQueryBuilderInterface::batchInsert()` without `$columns`

### ISSUE THREAD

**Issue by Tigrov** [yiisoft/db#772]
`$columns` can be obtained
1. from `$rows` if values are associative array
2. from `$table` if table shema found
3. or generate insert without columns if no columns found

Need to replace arguments 
from `DMLQueryBuilderInterface::batchInsert(string $table, array $columns, iterable $rows, array &$params = [])`
to `DMLQueryBuilderInterface::batchInsert(string $table, iterable $rows, array $columns = [], array &$params = [])`

This will allow to use the method this way `batchInsert($table, $rows)`

**Comment by vjik** [comment]
1 - 👍
2 - but we don't know order of fields in rows, also rows may contain not all fields. Seems, it's can lead to errors in user code.
3 - 👍

**Comment by Tigrov** [comment]
2. This is almost the same case as case 3, but we can get fields from table schema for casting type of values

**Comment by vjik** [comment]
> If no colums passed then means columns have order as in table schema

But why need columns in this case? Isn't that the equivalent to way 3?

**Comment by Tigrov** [comment]
> But why need columns in this case? Isn't that the equivalent to way 3?

Columns are needed for type casting and seems not all DBMS supports partial lists of values, but we can support them
