### ISSUE TITLE
Add SensitiveParameter attribute

### ISSUE THREAD

**Issue by samdark** [yiisoft/db#872]
https://github.com/yiisoft/db/blob/d1da00342a92e896f77e074ee039a711f1edb6a2/src/Driver/Pdo/PdoDriverInterface.php#L81

Add `#[\SensitiveParameter]` to password.

**Comment by heap-s** [comment]
Tried to fix but haven't contributed much in the past. Not so sure why checks are failing, if you could give some guidance I'll raise the PR again, if not, no worries

**Comment by samdark** [comment]
@heap-s it does't look like it's your fault. Something's broken in our tests pipeline. Pull request itself looked OK.

**Comment by heap-s** [comment]
@samdark I'll reopen today then to resolve this!
