### ISSUE TITLE
Add some id to SQL statements

### ISSUE THREAD

**Issue by uldisn** [yiisoft/db#97]
Reviewing the executed SQL statements in the debug toolbar or SQL log file is difficult to identify where they created. It would be very convenient to add id to the beginning. For example:
```php
        $sql = '
            -- ID::carsInWay --
        SELECT ...;
```

**Comment by uldisn** [comment]
I'll make pull request?

**Comment by samdark** [comment]
For yiisoft/db? You can try but note that the package isn't finished yet.

**Comment by Tigrov** [comment]
You can add info into log before exequte a query

```php
$logger->log(LogLevel::INFO, '-- ID::carsInWay --', [$category]);
$command->setSql('SELECT ...')->execute();
```
