### ISSUE TITLE
yii/di/AbstractContainer has been removed from yii/di

### ISSUE THREAD

**Issue by ac-dc** [yiisoft/db#98]
Yiisoft\\Db\\DataReader has a call of yii/di/AbstractContainer::configure in its constructor but yii/di/AbstractContainer has been completely removed from yii/di
https://github.com/yiisoft/di/commit/f8da6ffd052a1680270ce74482558f2d6d53563b

Could you, please, check it?

**Comment by samdark** [comment]
The change in yiisoft/di is correct but Yiisoft\Db\DataReader wasn't adjusted for it.

**Comment by ac-dc** [comment]
@samdark Also https://github.com/yiisoft/yii-core/commit/30c7bf170203805333d75ce789ff8b8c4fe4159b also causes the bug Fatal error: Class 'yii\base\Component' not found  in Connection.php because the Component class has been removed

**Comment by samdark** [comment]
That is correct. We're getting rid of Component.

**Comment by terabytesoftw** [comment]
Fixed,

Thanks
